<div id="Display"> <!-- Raph - look through and tell me if the table dem alright -->

    <div id="home"> <!-- Eiffel - Match the css ids and make it look decent pls-->

        <h1>Dashboard</h1> <input type="button" id="post" value="Post a Job" onclick=""><!-- Link "post a job" button to job page in onclick-->

    </div>

    

    <div>

        <h4>Available Jobs</h4>

        <table id = "details"> <!--Styling required for this element called details-->

            <tr>

                <th>Company</th>

                <th>Job Title</th>

                <th>Category</th>

                <th>date</th>

            </tr>

            

            

        </table>

    </div>

    

    

    <div>

        <h4>Jobs Applied For</h4>

        <table>

            <tr>

                <th>Company</th>

                <th>Job Title</th>

                <th>Category</th>

                <th>Date</th>

            </tr>

        </table>

    </div>


</div>