<style type="text/css">
    #home
    {
        position:absolute;
        background-color:#000;
        height:55px;
        width:100%;
        left:0px;
        top:0px;
        padding:10px;
    }
    #home h1
    {
        color:white;
    }
    
    #home input{
        position:absolute;
        right:30px;
        background-color:#000;
        border:none;
        border-radius:5px;
        height:40px;
        width:200px;
        color:#fff;
        font-weight:bold;
    }
    
    #Display #con
    {
        position:absolute;
        top:150px;
    }
    #Display #con1
    {
        position:absolute;
        top:250px;
    }
</style>
<div id="Display"> <!-- Raph - look through and tell me if the table dem alright -->

    <div id="home"> <!-- Eiffel - Match the css ids and make it look decent pls-->

        <h1>Dashboard</h1> <input type="button" id="post" value="Post a Job" onclick=""><!-- Link "post a job" button to job page in onclick-->

    </div>

    

    <div id="con">

        <h4>Available Jobs</h4>

        <table id = "details"> <!--Styling required for this element called details-->

            <tr>
                <th>Company</th>

                <th>Job Title</th>

                <th>Category</th>

                <th>date</th>
            </tr>

            

            

        </table>

    </div>

    

    

    <div id="con1">

        <h4>Jobs Applied For</h4>

        <table>

            <tr>

                <th>Company</th>

                <th>Job Title</th>

                <th>Category</th>

                <th>Date</th>

            </tr>

        </table>

    </div>


</div>